CREATE DATABASE lab_mysql;

CREATE TABLE CARS (
    ID_Car_table INT AUTO_INCREMENT PRIMARY KEY,
    VIN VARCHAR(50) NOT NULL,
    Manufacturer VARCHAR(50),
    Model VARCHAR(50),
    Car_year INT,
    Color VARCHAR(20)
);

CREATE TABLE CUSTOMERS (
    ID_Customer_table INT AUTO_INCREMENT PRIMARY KEY,
    Customer_ID INT NOT NULL UNIQUE,
    Name VARCHAR(50),
    PhoneNumber VARCHAR(50),
    Email VARCHAR(50),
    Address VARCHAR(50),
    City VARCHAR(50),
    State VARCHAR(50),
    Country VARCHAR(50),
    PostalCode INT
); 

CREATE TABLE SALESPERSONS (
    ID_Staff_table INT AUTO_INCREMENT PRIMARY KEY,
    Staff_ID INT NOT NULL UNIQUE, 
    Name VARCHAR(50),
    Store VARCHAR(50)
); 

CREATE TABLE INVOICES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Invoice_Number INT,
    Invoice_Date DATE,
    Car_ID INT,
    Customer_ID INT,
    SalesPerson_ID INT,
    FOREIGN KEY (Car_ID) REFERENCES CARS(ID_Car_table) ON DELETE SET NULL,
    FOREIGN KEY (Customer_ID) REFERENCES CUSTOMERS(ID_Customer_table) ON DELETE SET NULL,
    FOREIGN KEY (SalesPerson_ID) REFERENCES SALESPERSONS(ID_Staff_table) ON DELETE SET NULL
);