CREATE TABLE CARS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    VIN VARCHAR(50) NOT NULL UNIQUE,
    Manufacturer VARCHAR(50),
    Model VARCHAR(50),
    Car_year INT,
    Color VARCHAR(20)
);

CREATE TABLE CUSTOMERS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CustomerID INT NOT NULL UNIQUE,
    Name VARCHAR(50),
    PhoneNumber VARCHAR(50),
    Email VARCHAR(50),
    Address VARCHAR(50),
    City VARCHAR(50),
    State VARCHAR(50),
    Country VARCHAR(50),
    PostalCode INT
); 

CREATE TABLE SALESPERSONS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Staff_ID INT NOT NULL UNIQUE, 
    Name VARCHAR(50),
    Store VARCHAR(50)
); 

CREATE TABLE INVOICES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Invoice_Number INT,
    Invoice_Date DATE,
    Customer_ID INT,
    SalesPerson_ID INT,
    VIN VARCHAR(50),
    FOREIGN KEY (VIN) REFERENCES CARS(VIN) ON DELETE SET NULL,
    FOREIGN KEY (Customer_ID) REFERENCES CUSTOMERS(CustomerID) ON DELETE SET NULL,
    FOREIGN KEY (SalesPerson_ID) REFERENCES SALESPERSONS(Staff_ID) ON DELETE SET NULL
);