CREATE DATABASE if NOT EXISTS lab_mysql;
USE lab_mysql;

DROP TABLE IF EXISTS INVOICES;
DROP TABLE IF EXISTS SALESPERSONS;
DROP TABLE IF EXISTS CUSTOMERS;
DROP TABLE IF EXISTS CARS;

CREATE TABLE CARS (
    id_car_table INT AUTO_INCREMENT PRIMARY KEY,
    VIN VARCHAR(50) NOT NULL UNIQUE,
    manufacturer VARCHAR(50),
    model VARCHAR(50),
    car_year INT,
    color VARCHAR(20)
);

CREATE TABLE CUSTOMERS (
    ID_Customer_table INT AUTO_INCREMENT PRIMARY KEY,
    Customer_ID INT NOT NULL UNIQUE,
    Name VARCHAR(50),
    PhoneNumber VARCHAR(50),
    Email VARCHAR(50),
    Address VARCHAR(50),
    City VARCHAR(50),
    State VARCHAR(50),
    Country VARCHAR(50),
    PostalCode INT
); 

CREATE TABLE SALESPERSONS (
    ID_Staff_table INT AUTO_INCREMENT PRIMARY KEY,
    Staff_ID INT NOT NULL UNIQUE, 
    Name VARCHAR(50),
    Store VARCHAR(50)
); 

CREATE TABLE INVOICES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Invoice_Number INT,
    Invoice_Date DATE,
    Car_ID INT,
    Customer_ID INT,
    SalesPerson_ID INT,
    FOREIGN KEY (Car_ID) REFERENCES CARS(id_car_table) ON DELETE SET NULL,
    FOREIGN KEY (Customer_ID) REFERENCES CUSTOMERS(ID_Customer_table) ON DELETE SET NULL,
    FOREIGN KEY (SalesPerson_ID) REFERENCES SALESPERSONS(ID_Staff_table) ON DELETE SET NULL
);